export const SET_SESSION = 'SET_SESSION';
export const CLICK_REQUEST = 'CLICK_REQUEST';
export const CLICK_SUCCESS = 'CLICK_SUCCESS';
export const CLICK_FAILED = 'CLICK_FAILED';
export const LEADERBOARD_REQUEST = 'LEADERBOARD_REQUEST';
export const LEADERBOARD_SUCCESS = 'LEADERBOARD_SUCCESS';
export const LEADERBOARD_FAILED = 'LEADERBOARD_FAILED';
